# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gelfgren.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
gem "rspec", "~> 3.12"
gem "rubocop", "~> 1.50"
gem "rb_sys", "~> 0.9"
